---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpackerr
spec:
  chartRef:
    kind: OCIRepository
    name: unpackerr
  interval: 1h
  values:
    controllers:
      unpackerr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/unpackerr/unpackerr
              tag: 0.15.0@sha256:9f4cb99b78d8fe2d55f79c490a715e14a8a28d9868373dad642ca5adc2ac3e91
            env:
              TZ: Europe/Stockholm
              UMASK: 002
              UN_DEBUG: true
              UN_LOG_FILE: /logs/unpackerr.log
              UN_RADARR_0_URL: http://radarr.media.svc.cluster.local
              UN_SONARR_0_URL: http://sonarr.media.svc.cluster.local
              UN_WEBSERVER_METRICS: true
              UN_WEBSERVER_LOG_FILE: /logs/webserver.log
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 5656
    serviceMonitor:
      app:
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      logs:
        type: emptyDir
      media:
        type: nfs
        server: nas.wyde.network
        path: /mnt/hdd-media/Media
        globalMounts:
          - path: /data
