---
# This file is not managed by doco-cd because it can't manage itself.
# Instead it is deployed through the TrueNAS SCALE UI.

configs:
  poll-config.yml:
    content: |
      - url: https://github.com/pwyde/home-ops.git
        reference: refs/heads/main
        interval: 3600

networks:
  internal:
    name: internal
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.2.0/24
         gateway: 172.16.2.1

secrets:
  1pw_token:
    file: /mnt/hdd-data/Home/patrik/.config/doco-cd/1pw_token

services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.81.0@sha256:b4da9c65b0d069c79cb54162669d70b08a3bdad2e05cb1b63557ee28697ca8ef
    container_name: doco-cd
    configs:
      - source: poll-config.yml
        target: /poll-config.yml
    restart: unless-stopped
    environment:
      HTTP_PORT: 8080
      LOG_LEVEL: info
      POLL_CONFIG_FILE: /poll-config.yml
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN_FILE: /run/secrets/1pw_token
      DEPLOY_CONFIG_BASE_DIR: ./docker/truenas/
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - internal
    security_opt:
      - no-new-privileges
    ports:
      - 8080:8080
    secrets:
      - 1pw_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data

volumes:
  data: {}
