---
# Main Doco-CD instance. It is deployed by doco-cd-updater through
# .doco-cd.updater.yaml; the TrueNAS SCALE UI runs the updater instance.

configs:
  poll-config.yml:
    content: |
      - url: https://github.com/pwyde/home-ops.git
        reference: main
        interval: 3600

networks:
  internal:
    name: internal
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.2.0/24
         gateway: 172.16.2.1

services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.113.0
    container_name: doco-cd
    configs:
      - source: poll-config.yml
        target: /poll-config.yml
    restart: unless-stopped
    environment:
      HTTP_PORT: 8120
      LOG_LEVEL: info
      POLL_CONFIG_FILE: /poll-config.yml
      SECRET_PROVIDER: 1password
      SECRET_PROVIDER_ACCESS_TOKEN: ${SECRET_PROVIDER_ACCESS_TOKEN}
      SECRET_PROVIDER_CACHE_ENABLED: true
      SECRET_PROVIDER_CACHE_TTL: 6h
      DEPLOY_CONFIG_BASE_DIR: ./docker/truenas/
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - 8120:8120
      - 9120:9120
    networks:
      - internal
    security_opt:
      - no-new-privileges
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data

volumes:
  data: {}
