---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/alerts
  - ../../components/namespace
resources:
  # Flux-Kustomizations
  - ./audiobookshelf/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./navidrome/ks.yaml
