---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
networks:
  apps:
    external: true

services:
  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.151.0
    container_name: otel-collector
    restart: unless-stopped
    networks:
      apps:
    expose:
      - &metricsPort 8889
      - 4318
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.otel-collector.entrypoints: https
      traefik.http.routers.otel-collector.rule: Host(`otel.wyde.network`)
      traefik.http.routers.otel-collector.service: otel-collector
      traefik.http.routers.otel-collector.tls: true
      traefik.http.services.otel-collector.loadbalancer.server.port: *metricsPort
