---
# yaml-language-server: $schema=https://home-kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chartRef:
    kind: OCIRepository
    name: grafana
  interval: 1h
  values:
    deploymentStrategy:
      type: Recreate
    admin:
      existingSecret: grafana-secret
    grafana.ini:
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
      auth.anonymous:
        enabled: true
      news:
        news_feed_enabled: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - {name: Alertmanager, orgId: 1}
          - {name: Loki, orgId: 1}
          - {name: Prometheus, orgId: 1}
        datasources:
          - name: Alertmanager
            type: alertmanager
            uid: alertmanager
            access: proxy
            url: http://alertmanager-operated.observability.svc.cluster.local:9093
            jsonData:
              implementation: prometheus
          - name: Loki
            type: loki
            uid: loki
            access: proxy
            url: http://loki-headless.observability.svc.cluster.local:3100
            jsonData:
              maxLines: 250
          - name: Prometheus
            type: prometheus
            uid: prometheus
            access: proxy
            url: http://prometheus-operated.observability.svc.cluster.local:9090
            isDefault: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: database
            orgId: 1
            folder: Database
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/database
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: flux
            orgId: 1
            folder: Flux
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/flux
          - name: kubernetes
            orgId: 1
            folder: Kubernetes
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/kubernetes
          - name: networking
            orgId: 1
            folder: Networking
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/networking
          - name: prometheus
            orgId: 1
            folder: Prometheus
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/prometheus
          - name: security
            orgId: 1
            folder: Security
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/security
          - name: storage
            orgId: 1
            folder: Storage
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/storage
          - name: system
            orgId: 1
            folder: System
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/system
          - name: unifi
            orgId: 1
            folder: UniFi
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/unifi
    dashboards:
      database:
      default:
      flux:
        flux-operator-performance:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://raw.githubusercontent.com/controlplaneio-fluxcd/flux-operator/refs/heads/main/config/monitoring/dashboards/flux-performance.json
        flux-api-performance:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://raw.githubusercontent.com/controlplaneio-fluxcd/flux-operator/refs/heads/main/config/monitoring/dashboards/flux-k8s-api-performance.json
        flux-cluster:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/refs/heads/main/monitoring/configs/dashboards/cluster.json
        flux-control-plane:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/refs/heads/main/monitoring/configs/dashboards/control-plane.json
      kubernetes:
        etcd:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/22236/revisions/4/download
        kubernetes-api-server:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/15761/revisions/21/download
        kubernetes-coredns:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/15762/revisions/22/download
        kubernetes-global:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/15757/revisions/43/download
        kubernetes-namespaces:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/15758/revisions/46/download
        kubernetes-nodes:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/15759/revisions/40/download
        kubernetes-pods:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/15760/revisions/39/download
        kubernetes-pvc-stats:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://grafana.com/api/dashboards/23233/revisions/6/download
        kubernetes-volumes:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/11454/revisions/14/download
      networking:
        blackbox-exporter:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/7587/revisions/3/download
        cloudflared:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://grafana.com/api/dashboards/17457/revisions/6/download
        envoy-overview:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/24459/revisions/3/download
        envoy-upstream:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/24457/revisions/4/download
        envoy-downstream:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/24458/revisions/3/download
        external-dns:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/15038/revisions/3/download
        traefik:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/17346/revisions/9/download
      prometheus:
        prometheus:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/19105/revisions/9/download
      security:
        cert-manager:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/20842/revisions/3/download
      storage:
        ceph-cluster:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/2842/revisions/18/download
        ceph-osd:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/5336/revisions/9/download
        ceph-pools:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/5342/revisions/9/download
        minio:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://grafana.com/api/dashboards/13502/revisions/26/download
        truenas-scale-cgroups:
          datasource:
            - {name: DS_MIMIR, value: Prometheus}
          url: https://raw.githubusercontent.com/Supporterino/truenas-graphite-to-prometheus/refs/heads/main/dashboards/truenas_scale_cgroups.json
        truenas-scale-disk-insights:
          datasource:
            - {name: DS_MIMIR, value: Prometheus}
          url: https://raw.githubusercontent.com/Supporterino/truenas-graphite-to-prometheus/refs/heads/main/dashboards/truenas_scale_disk_insights.json
        truenas-scale-overview:
          datasource:
            - {name: DS_MIMIR, value: Prometheus}
          url: https://raw.githubusercontent.com/Supporterino/truenas-graphite-to-prometheus/refs/heads/main/dashboards/truenas_scale.json
        truenas-scale-temperatures:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://raw.githubusercontent.com/Supporterino/truenas-graphite-to-prometheus/refs/heads/main/dashboards/truenas_scale_temperatures.json
        volsync:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://grafana.com/api/dashboards/21356/revisions/3/download
      system:
        node-exporter-full:
          datasource:
            - {name: DS_PROMETHEUS, value: Prometheus}
          url: https://grafana.com/api/dashboards/1860/revisions/45/download
        smartctl-exporter:
          datasource:
            - {name: DS_VICTORIAMETRICS, value: Prometheus}
          url: https://grafana.com/api/dashboards/22381/revisions/1/download
      unifi:
        unifi-insights:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/11315/revisions/9/download
        unifi-network-sites:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/11311/revisions/5/download
        unifi-uap:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/11314/revisions/10/download
        unifi-usw:
          datasource: Prometheus
          url: https://grafana.com/api/dashboards/11312/revisions/9/download
    persistence:
      enabled: false
    plugins:
      - grafana-clock-panel
      - grafana-piechart-panel
      - grafana-worldmap-panel
    resources:
      requests:
        cpu: 30m
        memory: 128Mi
      limits:
        memory: 192Mi
    route:
      main:
        enabled: true
        hostnames:
          - "{{ .Release.Name }}.wyde.network"
        parentRefs:
          - name: envoy-internal
            namespace: network
    serviceMonitor:
      enabled: true
    testFramework:
      enabled: false
