# yaml-language-server: $schema=https://home-kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: joplin-secret
    template:
      data:
        ## joplin
        MAILER_HOST: "{{ .SMTP_HOST }}"
        MAILER_AUTH_USER: "{{ .JOPLIN_SMTP_USERNAME }}"
        MAILER_AUTH_PASSWORD: "{{ .JOPLIN_SMTP_PASSWORD }}"
        POSTGRES_HOST: &dbHost pg18-cluster-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DATABASE: &dbName joplin
        POSTGRES_USER: &dbUser "{{ .JOPLIN_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .JOPLIN_POSTGRES_PASSWORD }}"
        ## Postgres Init
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: joplin
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp
