---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
networks:
  internal:
    name: internal
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.2.0/24
         gateway: 172.16.2.1

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.11.1
    container_name: node-exporter
    restart: unless-stopped
    command:
      - --path.rootfs=/host/root
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.udev.data=/host/root/run/udev/data
      - --web.listen-address=0.0.0.0:9100
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    security_opt:
      - no-new-privileges
    network_mode: host
    volumes:
      - /:/host/root:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.14.0
    container_name: smartctl-exporter
    restart: unless-stopped
    environment:
      TZ: Europe/Stockholm
    privileged: true
    user: root
    security_opt:
      - no-new-privileges
    ports:
      - 9633:9633
    networks:
      - internal

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    container_name: cadvisor
    restart: unless-stopped
    command:
      - --housekeeping_interval=30s
      - --docker_only=true
      - --store_container_labels=false
    privileged: true
    devices:
      - /dev/kmsg
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

