---
- id: github-pwyde-home-ops-doco-cd
  execute-command: /config/github-push-doco-cd.sh
  pass-arguments-to-command:
    - # ref
      source: payload
      name: ref
    - # sha before
      source: payload
      name: before
    - # sha after
      source: payload
      name: after
    - # repository
      source: payload
      name: repository.full_name
    - # pusher name
      source: payload
      name: pusher.name
    - # pusher email
      source: payload
      name: pusher.email
    - # doco-cd webhook url
      source: string
      name: http://nas.wyde.network:8080/v1/webhook
  trigger-rule:
    and:
      - # Validate the webhook secret.
        match:
          type: payload-hmac-sha1
          secret: >-
            {{ getenv "GITHUB_WEBHOOK_SECRET" | js }}
          parameter:
            source: header
            name: x-hub-signature
      - # Trigger on pushes to main branch of pwyde/home-ops repo.
        and:
          - match:
              type: value
              value: push
              parameter:
                source: header
                name: x-github-event
          - match:
              type: value
              value: pwyde/home-ops
              parameter:
                source: payload
                name: repository.full_name
          - match:
              type: value
              value: refs/heads/main
              parameter:
                source: payload
                name: ref
